/*
    Nama	: Paramadina Mulya Majid
    Stambuk	: 13020180006
    Hari/Tgl	: Kamis, 11 Juni 2020
    Waktu	: 20.13 WITA
*/
package View;

import Source.ImplementMhs;
import Source.interfaceMhs;
import Source.koneksiDatabase;
import Source.mahasiswa;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author ACER
 */
public class dataSiswaFikom extends javax.swing.JFrame {

    DefaultTableModel model = new DefaultTableModel();
    interfaceMhs InterfaceMhs;
    List record = new ArrayList();
    int baris;
    String kJur;
    
    public dataSiswaFikom() throws SQLException {
        initComponents();
        koneksiDatabase.getConnection();
        InterfaceMhs = new ImplementMhs();
        Edit.setEnabled(true);
        Hapus.setEnabled(true);
        ambil_data(record = InterfaceMhs.getAll());
//        ambil_data_tabel();
        daftarJurusan();
    }
    void daftarJurusan() { 
        Object[] jur = {"Teknik Informatika", "Sistem Informasi"};
        for (int i = 0; i < jur.length; i++) { 
            CbJurusan.addItem(jur[i].toString()); 
        } 
        kJur = CbJurusan.getSelectedItem().toString(); 
    }
    
    public void ambil_data(List list) {
        Object data[][] = new Object[list.size()][4];
        int x = 0;
        for (Iterator it = list.iterator(); it.hasNext();) {
            mahasiswa p = (mahasiswa) it.next();
            data[x][0] = p.getNomhs();
            data[x][1] = p.getNama();
            data[x][2] = p.getJurusan();
            x++;
        }
        String judul[] = {"NOMHS", "NAMA", "JURUSAN"};
        jTable2.setModel(new DefaultTableModel(data, judul));
        jScrollPane2.setViewportView(jTable2);
    }
    
//    public void ambil_data_tabel() {
//        //supayakalodata di table di klikmakadata akanmuncullangsungdi textfieldnimnamaalamat
//
//        jTable1.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
//            @Override
//            public void valueChanged(ListSelectionEvent lse) {
//                baris = jTable1.getSelectedRow();
//                if (baris != -1) {
//                    isiFields();
//                }
//            }
//        });
//    }
    
//     public void isiFields() {
//        mahasiswa p = (mahasiswa) record.get(baris);
//        txtNomhs.setText(String.valueOf(p.getNomhs()));
//        txtNama.setText(p.getNama());
//        CbJurusan.setSelectedItem(p.getJurusan());
//    }

    public void bersih() {

        txtNomhs.setText("");
        txtNama.setText("");
        CbJurusan.setSelectedIndex(0);
        
    }
    void loadData() { 
        try { 
            record = InterfaceMhs.getAll(); 
        } catch (SQLException ex) { 
            Logger.getLogger(dataSiswaFikom.class.getName()).log(Level.SEVERE, null, ex); 
        } 
    }
    
    void statusAwal() { 
        bersih(); 
        loadData(); 
//        isiFields(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtNomhs = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        CbJurusan = new javax.swing.JComboBox<>();
        Edit = new javax.swing.JButton();
        Simpan = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        Cari = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        Hapus = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNomhs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomhsActionPerformed(evt);
            }
        });
        getContentPane().add(txtNomhs, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 680, 30));

        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        getContentPane().add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 260, 680, 30));

        CbJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));
        CbJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbJurusanActionPerformed(evt);
            }
        });
        getContentPane().add(CbJurusan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 230, 40));

        Edit.setFont(new java.awt.Font("Apricity", 0, 13)); // NOI18N
        Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-pencil-16.png"))); // NOI18N
        Edit.setText("EDIT");
        Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditMouseClicked(evt);
            }
        });
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });
        getContentPane().add(Edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 420, 170, 40));

        Simpan.setFont(new java.awt.Font("Apricity", 0, 18)); // NOI18N
        Simpan.setForeground(new java.awt.Color(102, 0, 102));
        Simpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-save-64.png"))); // NOI18N
        Simpan.setText("SIMPAN");
        Simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimpanActionPerformed(evt);
            }
        });
        getContentPane().add(Simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 210, 170, 70));

        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        getContentPane().add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 160, 210, 30));

        Cari.setFont(new java.awt.Font("Apricity", 0, 13)); // NOI18N
        Cari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-search-16.png"))); // NOI18N
        Cari.setText("CARI");
        Cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CariActionPerformed(evt);
            }
        });
        getContentPane().add(Cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(1069, 160, -1, 30));

        jTable2.setBackground(new java.awt.Color(204, 204, 255));
        jTable2.setForeground(new java.awt.Color(102, 0, 102));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NIM", "Nama", "Jurusan"
            }
        ));
        jTable2.setGridColor(new java.awt.Color(102, 0, 102));
        jTable2.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jTable2.setSelectionForeground(new java.awt.Color(102, 0, 102));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 420, 680, 220));

        Hapus.setFont(new java.awt.Font("Apricity", 0, 13)); // NOI18N
        Hapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-trash-can-16.png"))); // NOI18N
        Hapus.setText("HAPUS");
        Hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HapusMouseClicked(evt);
            }
        });
        Hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusActionPerformed(evt);
            }
        });
        getContentPane().add(Hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 480, 170, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Template.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomhsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomhsActionPerformed
        // TODO add your handling code here:
        Simpan.setEnabled(true);
        Edit.setEnabled(false);
        Hapus.setEnabled(false);
    }//GEN-LAST:event_txtNomhsActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
        Simpan.setEnabled(true);
        Edit.setEnabled(false);
        Hapus.setEnabled(false);
    }//GEN-LAST:event_txtNamaActionPerformed
    String stbAwal;
    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        try { 
            mahasiswa mhs = new mahasiswa(); 
            mhs.setNomhs(txtNomhs.getText().trim()); 
            mhs.setNama(txtNama.getText().trim()); 
            mhs.setJurusan(String.valueOf(CbJurusan.getSelectedItem()).trim()); 
            InterfaceMhs.update(mhs, stbAwal); 
//            this.statusAwal();
            JOptionPane.showMessageDialog(this, "data berhasil diubah");
            
            bersih();
            
            ambil_data(record = InterfaceMhs.getAll());
        } catch (SQLException ex) { 
//            System.out.println("Tidak Masuk");
            System.out.println(""+ex.getMessage());
            Logger.getLogger(dataSiswaFikom.class.getName()).log(Level.SEVERE, null, ex); 
        }
    }//GEN-LAST:event_EditActionPerformed

    private void SimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimpanActionPerformed
        
        try {
            if (txtNomhs.getText().equals("") && txtNama.getText().equals("") && CbJurusan.getSelectedItem().equals("")) {
                JOptionPane.showMessageDialog(this, "silahkan isi data yang akan ditambah");
            } else {
                mahasiswa p = new mahasiswa();
                p.setNomhs(txtNomhs.getText());
                p.setNama(txtNama.getText());
                p.setJurusan((String) CbJurusan.getSelectedItem());
                InterfaceMhs.insert(p);
                JOptionPane.showMessageDialog(this, "Data tersimpan");
                ambil_data(record = InterfaceMhs.getAll());
                bersih();
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, ex);
        }
    }//GEN-LAST:event_SimpanActionPerformed

    private void HapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusActionPerformed
        // TODO add your handling code here:
         try { 
            String Nomhs = txtNomhs.getText(); 
            InterfaceMhs.delete(Nomhs); 
//            this.statusAwal(); 
             ambil_data(record = InterfaceMhs.getAll());
            JOptionPane.showMessageDialog(this, "data berhasil dihapus"); 
        } catch (SQLException ex) { 
            Logger.getLogger(dataSiswaFikom.class.getName()).log(Level.SEVERE, null, ex); 
        }
    }//GEN-LAST:event_HapusActionPerformed

    private void EditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_EditMouseClicked

    private void HapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HapusMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_HapusMouseClicked

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
//        int x = jTable2.getSelectedRow();
//        txArea.setText(showDataLengkap(x+2));
    int baris = jTable2.getSelectedRow();
//    int kolom = jTable2.getSelectedColumn();
//    String dataTerpilih = jTable2.getValueAt(baris, kolom).toString();
    String kolom1 = jTable2.getValueAt(baris, 0).toString();
    String kolom2 = jTable2.getValueAt(baris, 1).toString();
    String kolom3 = jTable2.getValueAt(baris, 2).toString();
//    System.out.println(showDataLengkap(Integer.parseInt(kolom1)));
//    txArea.setText(showDataLengkap(Integer.parseInt(kolom1)));
    stbAwal = kolom1;
        txtNomhs.setText(kolom1);
        txtNama.setText(kolom2);
//        txtNomhs.setText(kolom3);
        if(kolom3.equals("")){
            CbJurusan.setSelectedIndex(0);
        }else if(kolom3.equals("Teknik Informatika")){
            CbJurusan.setSelectedIndex(1);
        }else if(kolom3.equals("Sistem Informasi")){
            CbJurusan.setSelectedIndex(2);
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void CariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CariActionPerformed
        String cari = txtCari.getText().trim();
        try {
            if(cari==null){
                ambil_data(record = InterfaceMhs.getAll());
            }else{
                ambil_data(record = InterfaceMhs.getSearch(cari));
            }
        } catch (SQLException ex) {
            Logger.getLogger(dataSiswaFikom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_CariActionPerformed

    private void CbJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbJurusanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbJurusanActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataSiswaFikom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataSiswaFikom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataSiswaFikom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataSiswaFikom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new dataSiswaFikom().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(dataSiswaFikom.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cari;
    private javax.swing.JComboBox<String> CbJurusan;
    private javax.swing.JButton Edit;
    private javax.swing.JButton Hapus;
    private javax.swing.JButton Simpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNomhs;
    // End of variables declaration//GEN-END:variables
}
